# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streetdoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='stdoc/bcover')),
                ('intro', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doc_permit_building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='stdoc/bcover')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetdoc.doc_building')),
            ],
        ),
        migrations.CreateModel(
            name='doc_permit_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='stdoc/cover')),
            ],
        ),
        migrations.AddField(
            model_name='doc_street',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_street',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doc_permit_street',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streetdoc.doc_street'),
        ),
        migrations.AddField(
            model_name='doc_building',
            name='stname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='streetdoc.doc_permit_street'),
        ),
    ]
