# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-01 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streetdoc', '0002_auto_20180629_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_permit_building',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='doc_permit_street',
            name='sid',
        ),
        migrations.AlterField(
            model_name='doc_building',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='doc_building',
            name='stname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='streetdoc.doc_street'),
        ),
        migrations.AlterField(
            model_name='doc_street',
            name='status',
            field=models.CharField(default='waiting', max_length=50),
        ),
        migrations.DeleteModel(
            name='doc_permit_building',
        ),
        migrations.DeleteModel(
            name='doc_permit_street',
        ),
    ]
