# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lost_street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='loststreet/cover')),
                ('intro', models.TextField(default='unknown')),
            ],
        ),
        migrations.CreateModel(
            name='ls_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='loststreet/gallery')),
                ('sname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='street.lost_street')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='street.lost_street'),
        ),
        migrations.AddField(
            model_name='comments',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
