# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='ls_comments',
        ),
    ]
