# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-02 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0002_auto_20180301_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='ls_comments',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
