# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0003_ls_comments_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ls_comments',
            name='sname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='street.lost_street'),
        ),
        migrations.AlterField(
            model_name='ls_comments',
            name='uname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
