# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_auto_20170907_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_tablespace='doc', max_length=50)),
                ('location', models.TextField(db_tablespace='doc')),
            ],
            options={
                'db_tablespace': 'doc',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(db_tablespace='works', max_length=50)),
                ('file_name', models.CharField(db_tablespace='works', max_length=50)),
                ('works_file', models.FileField(db_tablespace='works', upload_to='')),
            ],
            options={
                'db_tablespace': 'works',
            },
        ),
    ]
